### ISSUE TITLE
Fix parsing of logical negation, `not`

### ISSUE THREAD

**Issue by mehcode** [arrowlang/arrow#29]
`not a < b or c > d` should be parsed as `not (a < b) or c > d`; currently it is parsed as `(not a) < b or c > d`.

**Comment by joneshf** [comment]
That seems correct as it's currently parsing.

What are the associativity and precedence rules for function application and the comparison operators?

**Comment by Pholey** [comment]
(Not a) < b or c < d is the correct order, very few things have higher precedence than bitwise and logical not in most (if not all?) languages, the only things I could think of that have higher precedence in arrow would be []  (I.e array access !list[0]) and ()

**Comment by mehcode** [comment]
We have a unary negation operstor, `!`. `not` is meant for logical negation of boolean expressions as it does in python.

**Comment by mehcode** [comment]
Another note is that we don't have the concept of truthyness. `not x` would rarely be a legal expression while `not (x < y)` is always a legal expression.

**Comment by mehcode** [comment]
@pholey, this isn't an uncommon parse. Most languages parse it thus way if `not` is a keyword. We have `not` and `!`.

**Comment by mehcode** [comment]
All postfix operators have a higher precedence than unary operators. Function application, path navigation `x.y`, and subscript are examples. 

Comparison operators have the same precedence as they do in C.

**Comment by joneshf** [comment]
Can you explain what unary negation, and logical negation are? Why are two needed?

Can we put together a table of precedence and associativity? I'm not familiar with C's stuff.

**Comment by mehcode** [comment]
> Can you explain what unary negation, and logical negation are? Why are two needed?

We have 2 different kinds of negation operations: *arithmetic*, and *bitwise*. 

**Arithmetic** negation takes `320` and becomes `-320`.

**Bitwise** negation takes `320` and becomes `18446744073709551295` (for a 64-bit number).

**Logical** negation *is* bitwise negation (restricted to a single bit) and it is intended for use by boolean expressions.

Some languages use the `~` symbol to denote *bitwise* negation. I chose to use the `!` symbol so as to reserve `~` for some later purpose (not that I have one for it yet). As we already have the `!=` operator for inequality, I would expect programmers to assume that `!` would work on boolean expressions as well so `!` is overloaded to do so (which is only a type overload, the operation is still bitwise negation).

In the same vein, we have `&` (bitwise AND) and `|` (bitwise OR) that are overloaded to work with boolean and integral expressions. The precedence being lower than comparison but higher than assignment.

I prefer keywords where they make sense and following that I prefer `and` and `or` for use as combinators in selection expressions. I thought about it for awhile and (to me) it makes sense to have both `and` and `&`, and `or` and `|` if you make the keywords be short-circuiting and the symbols not.

Now that we have `and` and `or`, it follows to also have `not`. Again, this feels like a redundancy at first, however if you lessen the precedence of `not` to lower than comparison but higher than `and` and `or` then it becomes useful to negate a comparison without parenthesis: `not x > y` vs `!(x > y)`. We also do not have truthyness so `not x` (or `!x`) has the potential of not being correct whereas `not (x > y)` is always correct.

-----

Hopefully that explains my reasoning. 

> Can we put together a table of precedence and associativity? I'm not familiar with C's stuff.

Definitely. We need to hash out the specifics. I'll see about making a table later in the day and putting it up on an issue so we can review / hash it out.

**Comment by Pholey** [comment]
@mehcode, can you explain further (or provide a python example of what you mean)? Both logical and bitwise 'not' are unary operators, or operations that take a single operand, so saying '!' Is a unary operator doesn't tell me very much.. Do you mean for '!' To be bitwise?

**Comment by Pholey** [comment]
Can you provide a python example where not has a lower precedence than a Boolean expression?

**Comment by mehcode** [comment]
```python
x = 10
y = 20
assert ( not x  < y)  #= False
assert ((not x) < y)  #= True
```
